#!/usr/bin/env python3

# This file is part of gwe.
#
# Copyright (c) 2018 Roberto Leinardi
#
# gsi is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# gsi is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with gsi.  If not, see <http://www.gnu.org/licenses/>.

from gwe.nvidia import nvcmd
from gwe.nvidia.nvtarget import GPU

if __name__ == "__main__":
    nv = nvcmd.NVidiaControl()
    nv.open()
    gpu = GPU(0)
    for i in range(10000):
        nv.get_performance_modes(gpu)
        nv.get_gpu_utilization(gpu)
    nv.close()